### ISSUE TITLE
After provide vswhere-path, it prompt error: Unable to find MSBuild

### ISSUE THREAD

**Issue by P91491** [microsoft/setup-msbuild#101]
Dear all, would need some help, I have one Action to build the .NET Framework application using Windows self-hosted runner.
After I provide my vswhere-path, it promped me <Unable to find MS Build>.

![image](https://user-images.githubusercontent.com/118231094/206086906-a866ac56-e8f1-40e6-9eb7-555d75ee11fe.png)

I have installed Visual Studio 2015 and Microsoft Build Tools 2015 to achieve it but seems not working.
![image](https://user-images.githubusercontent.com/118231094/206087103-89fa0c1e-8d44-485f-924e-50bd03105fe7.png)
![image](https://user-images.githubusercontent.com/118231094/206087150-1db46149-a36f-4ebb-a721-cdfad0cc5a32.png)

Hereby I attached my .yml files to see is there any missed out in my .yml file

![image](https://user-images.githubusercontent.com/118231094/206087602-c47aab4c-e5fd-48d1-bb8e-f0e2ea48bd1a.png)

Thanks in advance guys.

**Comment by heaths** [comment]
What were you expecting to find? vswhere is designed to only work for VS2017 and newer. It can find if VS 2015 or older is installed, but can't check for components. The setup engine was completely rewritten between VS2015 and VS2017 to add those capabilities.

**Comment by P91491** [comment]
> Also, since you're using a self-hosted agent that you control, just make sure you add the location of MSBuild to your PATH yourself and you don't need an action to locate it.

Hi @heaths , yes I am using self-hosted agent. Is it mean if I  can skip the step setup-msbuild and proceed to remaining?
![image](https://user-images.githubusercontent.com/118231094/206325426-48348dc0-10ee-4c96-9c8a-a727f247116f.png)

The location of MSBuild is as below:
![image](https://user-images.githubusercontent.com/118231094/206325615-cddac4d2-7c4d-4092-9670-6ba5cff4729c.png)

If I define path like this is it ok?
![image](https://user-images.githubusercontent.com/118231094/206325692-b283b3b8-0a5b-43ef-9c95-6f63b30c59b4.png)
![image](https://user-images.githubusercontent.com/118231094/206325777-ca798147-a43f-4e1e-be35-2f918d412125.png)

**Comment by P91491** [comment]
Hi @heaths , thanks, I able to proceed after remove step [Setup-msbuild] as mentioned above. 
![image](https://user-images.githubusercontent.com/118231094/206327716-0efef552-7b73-4589-abb7-d2d70d44b5c0.png)

But when doing step upload artifact, it faced path issue. Actually for runner where should I point to upload for published webapp?

**Comment by P91491** [comment]
Hi @heaths , I do as below, not sure the flow correct or not, 
1) in my local Visual Studio I publish the project to Runner Instance folder.
![image](https://user-images.githubusercontent.com/118231094/206334702-70d3cfd7-be52-4efa-90e3-6a8bc38218e8.png)


2) Commit and synch with github from my local repo
![image](https://user-images.githubusercontent.com/118231094/206334850-0e66e8d3-bd15-44e7-97d6-eec3a64b11a7.png)


3) Trigger the Action to start run the steps, it is success and the artifacts is upload to server from my STEP (1) new created folder.
![image](https://user-images.githubusercontent.com/118231094/206334947-b5b66008-4134-4578-9c95-6606ce9c5c2e.png)


I not sure the flow is it correct or not...kindly enlighten me if any wrong. Thanks.
And I wonder where is the artifacts upload to? The server is refer to where?

**Comment by heaths** [comment]
I'm sorry, I do not have any insight into the actions/upload-artifact task any more than what's documented. I recommend you open an issue or start a discussion in their repo.

**Comment by P91491** [comment]
Thanks @heaths ,i think my issue resolved by remove the steps. Just set as environment variables to point the MSBuild path resolve this.
