### ISSUE TITLE
MvcBuildViews-setting is getting ignored by MSBuild

### ISSUE THREAD

**Issue by pekkasin** [microsoft/setup-msbuild#107]
Hello,

I've run into a problem regarding MSBuild and MvcBuildViews-setting. In short, the github action for msbuild doesn't seem to respect the MvcBuildViews-setting defined in the project's .csproj-file. I'll try to list the steps to reproduce the problem below:

1. Create a new ASP.NET Web Application with MVC project template.
2. Observe that MVC view precompilation is set to `false` by default in the project's .csproj -file like so:
    `<MvcBuildViews>false</MvcBuildViews>`
3. Observe that further down the same .csproj-file a build target `MvcBuildViews` is defined like so:
`  <Target Name="MvcBuildViews" AfterTargets="AfterBuild" Condition="'$(MvcBuildViews)'=='true'">
    <AspNetCompiler VirtualPath="temp" PhysicalPath="$(WebProjectOutputDir)" />
  </Target>`
4. Introduce an arbitrary syntax error to any of the .cshtml-files in the project to trigger compiler warnings when using msbuild with Mvc view precompilation (right now that should be set to `false` according to the configuration above.
5. `nuget restore` the dependencies if Visual Studio didn't do it for you.
6. Try to build the solution locally with `msbuild.exe ProjectName.sln`. The compilation should complete without errors.
7. Define a GitHub Action for the solution (latest version of setup-msbuild or something older, doesn't matter) and try the same compilation process via setup-msbuild GitHub Action.
8. The compilation fails because of the syntax error in the .cshtml -file, **which implies that precompilation is happening despite a setting to the contrary in the .csproj-file.** 

This discrepancy between the results locally and in GitHub Actions is confusing since they both use the same version of MSBuild. **The build target defined above has the condition set that `MvcBuildViews` should be `true` for the precompilation to happen.** 

I tried out all the different "permutations" of the two settings (MvcBuildViews-element and the build target condition) both locally and in GitHub Actions and I got the following results (if the setting and condition match, the precompilation should happen, if I've understood correctly):

```
           | <MvcBuildViews> | Build target condition | Did precompilation happen?
------------------------------------------------------------------------------------
Local      |    False        |         False          |          Yes 
GH Actions |                 |                        |          No
-------------------------------------------------------------------------------------
Local      |    True         |         False          |          No
GH Actions |                 |                        |          No 
------------------------------------------------------------------------------------
# This is the default setting that the project template comes with
Local      |    False        |         True           |          No
GH Actions |                 |                        |          Yes
-----------------------------------------------------------------------------------
Local      |    True         |         True           |          Yes
GH Actions |                 |                        |          Yes
-----------------------------------------------------------------------------------
```
So the local run of MSBuild worked just as expected with the precompilation only happening when the MvcBuildView-setting matched the build target condition. On GH Actions the results varied quite a bit. **It basically looks like MSBuild on GH Actions behaves as if the** `<MvcBuildViews>`-**setting is hard coded to be** `true` (ignoring whatever is actually set in the .csproj-file). I also tried to set the MvcBuildViews-parameter by calling GH Action MsBuild with `/p:MvcBuildViews=false` but that did nothing (locally that also worked just as expected. 

Am I missing something? I'm specifically trying to **disable** Mvc view precompilation. Of course the workaround seems to be to set `MvcBuildViews `to `True `and build target condition to `false`, for example, but I'd like to understand the root cause of why the mcvbuildviews-setting is getting ignored when using GitHub Actions, but not locally. Any ideas? Or is it an actual bug?

**Comment by timheuer** [comment]
Hi @pekkasin can you open this issue on `dotnet/msbuild` as this seems to be related to functionality of msbuild in general versus this action. This repo is only for the setup of the msbuild path which if you are using this appears to be working and now you are facing an issue with msbuild itself and certain project properties.

unfortunately I cannot transfer the issue directly so you’ll have to reopen on that repo. Thanks!

**Comment by pekkasin** [comment]
Hey @timheuer, sure I can! I wasn't sure which one to post the issue to, so thanks for pointing me in the right direction. :)
