### ISSUE TITLE
Add action typing

### ISSUE THREAD

**Issue by krzema12** [microsoft/setup-msbuild#109]
I'm looking to get your action first-class supported by https://github.com/krzema12/github-workflows-kt, a Kotlin DSL to write GitHub Action workflows.

They came up with a way to reduce operational load when keeping library's action wrappers in sync with actions' inputs and outputs. The solution includes onboarding https://github.com/krzema12/github-actions-typing. It's as easy as adding an extra YAML file to your repository root, and adding a simple GitHub workflow that validates this new file. Thanks to this, the code generator in the Kotlin DSL can fetch typing info provided by you instead of them, which has a number of benefits. It has no negative effects on current action consumers, they continue to use the action via regular GitHub API, as if the file wasn't there.

In this feature request, I would like to ask you if you're open to introducing such typings in your action. You wouldn't be first - there're already other actions using it, like e.g.: https://github.com/Vampire/setup-wsl or https://github.com/ReactiveCircus/android-emulator-runner (full list [here](https://github.com/krzema12/github-actions-typing/network/dependents)).

If your answer is "yes", feel free to either add it yourself, or let me know - me or some of the library contributors would be happy to post a PR. They're also open to any kind of questions and feedback.

**Comment by timheuer** [comment]
Hi @krzema12 thank you for submitting an issue here. We will decline at this time to include this in this repo.  This action is very focused and we desire to keep the source here focused on the specific task.

**Comment by krzema12** [comment]
@timheuer I believe we have a misunderstanding here. Adding the typings won't make the action less focused in any way, and instead it will make it easier for certain users to _consume_ the action.

**Comment by Vampire** [comment]
@timheuer let me also chime in as an early adopter.

The only change and effect on your action is an additional file `action-types.yml` where you formally describe the types of inputs and outputs of your action, instead of just using prose.
(Usually you also have one additional GitHub workflow that does some consistency checks for the type file.)

This allows consumers of your action to see exactly and unambiguously which types your action expects and provides.

Additionally it allows libraries like `github-workflows-kt` (which allows to write GitHub Workflow files in Kotlin instead of YAML) to process these type information programmatically to automatically generate a class so that users of that library can easily and type-safely use your action.

**Comment by LeoColman** [comment]
My two cents as an early adopter and a contributor that tries to onboard `action-types.yml` to other repositories:

> The only change and effect on your action is an additional file action-types.yml where you formally describe the types of inputs and outputs of your action, instead of just using prose.

This point is utmost.  I'd kindly suggest you to reconsider "This action is very focused" @timheuer, as this change stabilizes the action even more!

**Comment by timheuer** [comment]
My understanding based on looking is this would require an additional workflow to be executed on this repo.  Is that not the case?

**Comment by krzema12** [comment]
The workflow is not strictly required, but highly recommended to ensure the typings are valid and that they match the inputs from action.yml. It's a very simple workflow. Is it problematic in any way? It still doesn't influence the complexity of the action itself.

**Comment by timheuer** [comment]
There is a bit more overhead for compliance on this repo -- it's maintained by 2 people and not our primary roles, so we're not eager to add things that cause more overhead for us ;-).  I'll take a re-look at adding the types (PR is appreciated) but would not likely add a workflow to the repo.

**Comment by krzema12** [comment]
Thanks! 🙇

**Comment by krzema12** [comment]
@timheuer for this to work on our end, this change needs to be released, i. e. available from your major version tag. Are you planning to release soon? If not, could you do it?

**Comment by timheuer** [comment]
I'll see if I can push a release later today...in a bunch of meetings for a bit.

**Comment by timheuer** [comment]
Released 1.3.1 and updated v1/v1.3 tags

**Comment by Gakk** [comment]
@timheuer I see that version 1.3.1 is tagged, but it is not created as a release on GitHub. Have you stopped creating releases?

This results in @dependabot pull requests being without release notes 😲

**Comment by timheuer** [comment]
@Gakk - yes, sorry...will try to be better here.
