### ISSUE TITLE
msbuild C/C++ compiler license

### ISSUE THREAD

**Issue by rcotterill** [microsoft/setup-msbuild#114]
Hello,

Is there a license requirement to use the setup-msbuild Action to compile C/C++ ?

The reason why is we need to share a repo that uses it with a company that does not have Visual Studio licenses. We are concerned that the C/C++ build tools installed on GitHub servers and used by msbuild might not be licensed.

Thank you,
Richard

**Comment by timheuer** [comment]
Hi @rcotterill -- thanks for asking this.  This action does not carry any of the C++ toolset at all, it is merely a script that is intended to run on an agent that already has Visual Studio build tools installed, either in the hosted sense (as in GitHub Actions or Azure Pipelines agents) or via self-hosted configuration settings.  So as such, the better place to ask this question is actually over on the runner repository: https://github.com/actions/runner-images which is where the actual toolsets are installed into the hosted agents.  `setup-msbuild` is just a tool that then looks for MSBuild instances and adds it to `PATH` on the machine.

**Comment by rcotterill** [comment]
Hi @timheuer - I'll do that thank you :)

Best Regards
Richard
