### ISSUE TITLE
Prerelease too old

### ISSUE THREAD

**Issue by larioteo** [microsoft/setup-msbuild#119]
I have the problem that I am using the lates VS prerelease Version, but the actual action on github is far behind.

Local v17.8 preview 1
Github v17.6.3

https://github.com/OmniVortexStudios/ultra/actions/runs/5843382735

Is there a way to target really the latest release, am I overviewing something in the docs?

**Comment by timheuer** [comment]
Hi @larioteo -- looks like you are using a hosted runner.  You can see the software of the hosted runner you are using as it emits this in the log: https://github.com/OmniVortexStudios/ultra/actions/runs/5843382735/job/15845482796#step:1:10 -- the `windows-2022` runner still has 17.6 installed on it and I suspect it will be updating to 17.7 sometime soon.

This will still only have 17.7 so if you are in need of something specific for 17.8, you'll need to target a runner that has that software on it.  Presently the `windows-2022` images don't contain pre-release software so you'll need to find a way to either install that on your image during one of your steps, or use a self-hosted runner with your target software installed.

Using the `vs-prerelease` tag on this action still requires the pre-release to exist on the runner per the docs, but it does not exist in the image you are using for the run.

Hope this helps! If you have suggestions to modify the documentation on this flag (https://github.com/microsoft/setup-msbuild#use-pre-release-versions-of-visual-studio-optional) to make it more clear than the statement about needing the software to be there, I'm happy to make some changes to make it clearer.

**Comment by larioteo** [comment]
OK, yeah seems reasonable with your explanation. I had no clue that the default hosted runner is that far behind. I'm relatively new to GitHub Actions so I thought that the action includes by default a runner which supports the latest releases of msbuild. As o read that the action is using vswhere i thought there should be by default multiple versions installed.

Maybe it would help newbies like me to add a note at the beginning of the documentation about runners. This action was my first so I read your documentation without any knowledge how actions really work.

**Comment by timheuer** [comment]
> Maybe it would help newbies like me to add a note at the beginning of the documentation about runners. This action was my first so I read your documentation without any knowledge how actions really work.

I'll edit that to point to the included software (or where to find it) and try to make clear.

Yes, the runners do have the 'latest' but it is about ~1 week behind releases.  So 17.7 (latest release) should be there soon.  But the hosted runners do not have preview releases so that doesn't count toward 'latest' here unfortunately.

And yep, `vswhere` will find what is needed, provided it actually is there ;-)

**Comment by timheuer** [comment]
Added this new note in the README: https://github.com/microsoft/setup-msbuild#runners-and-included-software
