### ISSUE TITLE
'cl.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gaebor** [microsoft/setup-msbuild#121]
This github action puts `msbuild` in the `PATH` but not other compiler tools, like `CL`.

Is this intended? How can I use `CL` for compiling in a github workflow?

This caused the problem for me: https://github.com/gaebor/primes/blob/b8f0f58970529bd89a0ace7191e6d9ef2cbbc223/.github/workflows/test.yaml#L32-L42

```shell
where msbuild  # success
where cl       # cannot find
```

But `msbuild` can clearly use `cl` during the build.

**Comment by timheuer** [comment]
Hi @gaebor, this action only sets the path for MSBuild...it does not add the other VC tools paths (which are not in the same location). There are a few other community actions that have configured these such as https://github.com/seanmiddleditch/gha-setup-vsdevenv (that do some vcvarsall type activity).

I understand that msbuild clearly can use a set of other tools (cl, etc), but for this action we've focused only on msbuild and not expanding as of now.  We get a few requests for other paths (eg test), etc. but keeping this solidly focused on the name -- msbuild

Going to just close this as we are not planning on changing to expand support **in this action**

**Comment by gaebor** [comment]
Thanks 🤗
