### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by kawon7317** [microsoft/setup-msbuild#123]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: microsoft/setup-msbuild@v1.3.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by paoloverdini97** [comment]
I agree, +1

**Comment by JochemPalmsens** [comment]
I'm getting the same warning from Github
Is it as simple as changing 'node16' to 'node20' in https://github.com/microsoft/setup-msbuild/blob/main/action.yml ?

**Comment by timheuer** [comment]
Hey thanks for the PR @kawon7317...I'm hoping to merge/release this tomorrow.

**Comment by timheuer** [comment]
Thanks...released as v1.3.2, updated v1/v1.3 tags as well.
