### ISSUE TITLE
Switching the version to Node20 is an unexpected breaking change released as a patch version.

### ISSUE THREAD

**Issue by cliffchapmanrbx** [microsoft/setup-msbuild#125]
Hi team,

[Version 1.3.2 of this action](https://github.com/microsoft/setup-msbuild/releases/tag/v1.3.2) switched the required runtime from [Node16 to Node20](https://github.com/microsoft/setup-msbuild/pull/124). This is a backwards-incompatible breaking change.

We use GitHub Enterprise Server on-prem which has a different release cadence and software support relationship with the GitHub Actions Runners. We have a number of complex builds that we're working on migrating to Node20. 

As Node20 changes runner requirements most GitHub Actions have chosen to release a major version bump. The unexpected _patch_ version change caused us some headaches as we ran around fixing things.

Would it be possible to release a revert for the v1 action, and publish a separate v2 version with the Node20 change?

**Comment by timheuer** [comment]
Hi @cliffchapmanrbx thanks for this. Apologies for unintended impact of this. In hindsight I should have known not to patch. 

Interim is that v1.3.1 should unblock you for now. 

Your request is reasonable and I’ll take that action.

**Comment by cliffchapmanrbx** [comment]
> Interim is that v1.3.1 should unblock you for now.

Yep we've been updating our workflow files to pin the working version as a workaround, it's just a lot of effort across our codebases :)

> Your request is reasonable and I’ll take that action.

Thank you very much for the quick response! We've gotten a lot of mileage out of this action and appreciate it continuing to be supported.

**Comment by timheuer** [comment]
Thanks again @cliffchapmanrbx for raising the concern.  The following action was taken:

v1.3.3 created (and v1 and v1.1 tags updated) to revert back to `node16`
v2 (v2.0.0) created with the `node20` change and no other functionality changes

I apologize for this oversight of not being mindful of the potential impact in even a minor change (let alone patch version).
