### ISSUE TITLE
Avoiding MSBuild version with GitHub action

### ISSUE THREAD

**Issue by filippovichv** [microsoft/setup-msbuild#128]
Currently in my github actions i am using

" uses: microsoft/setup-msbuild@v1"

instead of updating this to newest version i was wondering if it's good idea to use `@main` insted ,to avoid future updates for news versions.

"uses: microsoft/setup-msbuild@main"

it seems working but i was not able to find that anyone uses this - what are risks ?

**Comment by timheuer** [comment]
Hi @filippovichv  thanks for the question. The general guidance is not to use `@[branch]` version dependencies in your flows as it could float. In fact, using 'main' could likely get you more updates than expected. It is not a semantic versioned branch. Now granted, this particular repo doesn't update often, but it would not be good guidance to follow.

v1 means v1 + v1.x + v1.x.x
v1.x means v1.x + v1.x.x
v1.x.x means v1.x.x

So if you want the MOST predictable versioning you'd snap to a major.minor.revision version but you wouldn't get updates until you update yourself manually.

Hope this helps?

**Comment by filippovichv** [comment]
i am trying to avoid code change every time version is not supported anymore   .. is there a way to avoid version altogether  like  use @lates  or  something   with: fetch-tags: "Latest"

**Comment by timheuer** [comment]
The best way is actually to snap to a major. something like `@latest` would possibly introduce you to breaking changes that would impact you (as what happened to others with the nodejs change in the runners, hence a version bump). So my recommendation would be to use an `@v` version...ideally the latest (v2).  That way you're getting the 'latest' of that version without breaking changes that may affect you and can consciously change to a later major version.

**Comment by filippovichv** [comment]
thank you

**Comment by timheuer** [comment]
No problem @filippovichv I'll close this issue now, feel free to keep discussing here if needed. I hope I explained it well enough!
