### ISSUE TITLE
Similar approach for mstest?

### ISSUE THREAD

**Issue by MarcelJurtz** [microsoft/setup-msbuild#13]
Is there a similar option available to set up mstest?

Edit: For everyone that has the same usecase, I'm currently using this: https://github.com/vrnobody/Setup-DotNetFrameworkEnv
which seems to work fine.

**Comment by timheuer** [comment]
@MarcelJurtz we thought about leveraging this as a general 'setup-visualstudio' aspect, but for now focused on MSBuild specifically for this action.  Not ruling out we could/should do this for mstest, but for now keeping this particular repo isolated for MSBuild discovery only.

**Comment by henryiii** [comment]
This probably also means that there's no way to get vcvarsall.bat or similar functionality, I would expect, until we have a setup-visualstudio action? I can request that [this page be changed](https://cibuildwheel.readthedocs.io/en/latest/cpp_standards/#windows-and-python-27), which I think wrongly suggests that this action can be used to prepare a python dev environment.

**Comment by timheuer** [comment]
Closing this as 'won't fix' in this action.
