### ISSUE TITLE
How to use Preview Version?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/setup-msbuild#138]
i need to use preview version of msbuild which is 
```
MSBuild version 17.13.0-preview-24568-05+37fc8280d for .NET Framework
17.13.0.56805
```
but i dont know how to use this version!
this is not working:
`vs-version: '[17.13,18.0)'`

**Comment by timheuer** [comment]
Hi @ghost1372 a few things have to be satisfied as noted in the README: https://github.com/microsoft/setup-msbuild#use-pre-release-versions-of-visual-studio-optional

If you are using the hosted runners, there is no preview version that is by default on the machine, so this will not work as noted in the docs. If you are using a self-hosted runner or other means and can validate you have the version on the agent machine, then follow the instructions to use `pre-release` and version numbering.

Can you tell me if you are using the hosted runners?

**Comment by ghost1372** [comment]
I am new in github actions but i think i am in hosted running.

**Comment by timheuer** [comment]
@ghost1372 got it! Welcome to GitHub Actions! -- yes sounds like you are using the hosted runners (meaning you have a repo that is just running the actions without any further effort from you and using `windows-latest`).  So for you, unfortunately you cannot use any preview of VS on hosted runners as the software is just not present.  

Hope this helps at least understand the flow.  You could explore self-hosted runners, but you'd be responsible for maintaining the infrastructure of the image and hosting it.  I'll close this issue now that we've explained how this script expects the software to be there at least.
