### ISSUE TITLE
vs-version is not working and MSBuild always use latest 

### ISSUE THREAD

**Issue by Ram-Maersk** [microsoft/setup-msbuild#18]
Hi, 

I am just running one build pipeline for unlimited parts repo with VS2017. But I am facing issues with the wrong selection of the VS version and so build failed. Here is the screenshot.
![image](https://user-images.githubusercontent.com/65896097/84655063-93122980-af10-11ea-9002-04b7ae0928f7.png)

**Comment by timheuer** [comment]
@Ram-Maersk Is this a hosted agent?

**Comment by Ram-Maersk** [comment]
@timheuer No, it is not self hosted. It is GitHub hosted runner. Windows-latest.

**Comment by timheuer** [comment]
Okay that makes sense now. The hosted agents only have latest version of VS on them. The version flag is really there in the event that changes and/or you have self-hosted agents.

**Comment by Ram-Maersk** [comment]
@timheuer  Ohh. That looks difficult then if we want to build VS 2017 solution using Github runners as the solution works with VS 2017 only. Do you know any other possibilities?

**Comment by timheuer** [comment]
@Ram-Maersk You can use the `windows-2016` image which has VS 2017 installed per https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md and then just omit the `version` argument here.
