### ISSUE TITLE
Unable to find MSBuild on hosted runners

### ISSUE THREAD

**Issue by ranjjose-chaz** [microsoft/setup-msbuild#20]
The MSBuild dependency step keeps failing.

This is from my GitHub-actions YML file:
The host is a **`Windows_Server-2019`** VM on **AWS**
VS flavour installed is **Visual Studio 2019 Community Edition with License: Visual Studio Community**

    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'  

resulting in the error in the step:

> Run microsoft/setup-msbuild@v1.0.1
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
##[error]Unable to find MSBuild.

I did add `MSBuild` location in the system path variable as well.

What am I missing?
Thanks for the consideration

I had asked this originally as a [comment](https://github.com/microsoft/setup-msbuild/issues/7#issuecomment-665189100) on #7

**Comment by heaths** [comment]
Can you log into the machine and just run the same command line? What do you get for results and `%ErrorLevel%` (cmd; $LastExitCode in PowerShell)?

**Comment by ranjjose-chaz** [comment]
OK! I could fix the issue by doing the following changes:
Step1 was to add the correct **MSBuild path into the environment variables**. 
I got the correct path by running, `dir HKLM:\SOFTWARE\Microsoft\MSBuild\ToolsVersions\` 
After this build started to run on PowerShell however it failed due to ToolsVersion mismatch. I fixed this by manually downloading and installing the required version.  
After this, the build started to work command line as well via  GitHub-actions

**Comment by caibinwav123456** [comment]
OK I've got the same issue when running the Action with a yml file msbuild.yml:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.4,16.5)'
And it got the output:
[command]C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest -version [16.4,16.5)
##[error]Unable to find MSBuild.
what can I do to check if it was because the msbuild path was not added to the environment variables? or because of other reasons?

**Comment by caibinwav123456** [comment]
PS: is this the version relationship between VS version and VC version?
VC10.0 | VS2010
VC16.0 | VS2019
I am expected to use VS2010 as the developing environment so how to modify the vs-version: '[16.4,16.5)' annotation to match the VS version?
[msbuild.zip](https://github.com/microsoft/setup-msbuild/files/6521785/msbuild.zip)

**Comment by timheuer** [comment]
@caibinwav123456 are you using a self-hosted runner or a hosted one on GitHub?  If self-hosted, do you have more than one version of VS installed on the agent?

**Comment by heaths** [comment]
You need to change the version to cover the range of product you want, e.g. `[10.0,11.0)` to select only VS2010 instances. And, yes, with the except of legacy VC14.0 support in VS2017+ (not sure for how much longer), VC version corresponds to VS version.

Honestly, though, if you just want VC10 set up and are using a custom host, you should know where VS2010 is installed and probably just better off launching the developer command prompt or just vcvars32.bat (I believe that was the main env vars script back then). Using vswhere to find what you already know is installed and where on an environment you own is just extra steps.

**Comment by caibinwav123456** [comment]
I am running this on a github hosted server agent as an github action and an minimized set of building tools (most likely a commandline tool package) is ok for me so I'm looking for tools like msbuild. Do I need to install the whole IDE software developing environment(eg. VS2010) on the github server agent?

Another problem is that I usually want to install a stand-alone windows-build-tools package including Platform toolset, WindowsSDKs, etc. to work with msbuild. Do these tools need to be installed and configured extraly?

I've not used msbuild or the developer command prompt to build my vs projects in cmdline on my own pc at present. Is there any way I can get logged into the server machine so that I can try it directly?

THX

**Comment by timheuer** [comment]
@caibinwav123456 If you are using GitHub's agents, you don't need to specify the version flag...as there is only one version of Visual Studio on `windows-latest` so you'll get that one.  And if you are using the hosted agents, no you don't have direct access to the machine.  If you haven't used MSBuild locally you may want to familiarize yourself with the commands as you'll still need to specify them.  You can test locally by running `msbuild <path-to-your-solution-or-project>` and add whatever options you need (configuration, etc.).  You can see an example here (although this adds web publishing) https://github.com/timheuer/SimpleFrameworkApp/blob/master/.github/workflows/build.yml#L34

**Comment by caibinwav123456** [comment]
OK，I've done it! Then I want to package the compilation output and publish it to a different repository. What shall I do?
Is there any templates?

**Comment by timheuer** [comment]
@caibinwav123456 I'm not sure if there are templates, but I would start looking at different documentation for the different repository you are trying to publish to, etc.

**Comment by P91491** [comment]
> OK! I could **fix the issue** by doing the following changes: Step1 was to add the correct **MSBuild path into the environment variables**. I got the correct path by running, `dir HKLM:\SOFTWARE\Microsoft\MSBuild\ToolsVersions\` After this build started to run on PowerShell however it failed due to ToolsVersion mismatch. I fixed this by manually downloading and installing the required version. After this, the build started to work command line as well via GitHub-actions

Hihi, I new to github action and now trying to build my .Net Framework application in Windows self-hosted runner program. I faced the same issue whereby not able to find the MSBuild after define path for vswhere.
![image](https://user-images.githubusercontent.com/118231094/206079783-d25a0b65-e083-4187-90de-77a865e41d85.png)

Hereby I share out my .yml file content.
`name: Build PIMS
on: 
    workflow_dispatch:
    release:
      types: [push]
jobs:
  build:
   
   runs-on: ['self-hosted', 'Windows', 'X64']
 
   steps:
    - uses: actions/checkout@v3
      name: Checkout Code
      
    - name: setup-msbuild
      uses: warrenbuckley/Setup-MSBuild@v1
      with:
            vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'

    - name: Setup NuGet.exe for use with actions
    # You may pin to the exact commit or the version.
    # uses: NuGet/setup-nuget@fd9fffd6ca4541cf4152a9565835ca1a88a6eb37
      uses: NuGet/setup-nuget@v1.1.1
     
    - name: Restore NuGet Packages
      run: nuget restore PIMS.sln
 
    - name: Build and Publish Web App
      run: msbuild PIMS.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Mewah
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: C:\Users\P91491\Desktop\Github Project\mwgithub01\Publish`
        
        
 Any solution to resolve the issue not able found MSBuild path?

**Comment by heaths** [comment]
You're using a different action: `warrenbuckley/Setup-MSBuild@v1`. You'd need to either replace that with `microsoft/setup-msbuild@v1` or file an issue on https://github.com/warrenbuckley/Setup-MSBuild. I may be biased since I was the VS setup architect and wrote vswhere, but I'd recommend this one which @timheuer does a great job of keeping up to date.

**Comment by P91491** [comment]
> You're using a different action: `warrenbuckley/Setup-MSBuild@v1`. You'd need to either replace that with `microsoft/setup-msbuild@v1` or file an issue on https://github.com/warrenbuckley/Setup-MSBuild. I may be biased since I was the VS setup architect and wrote vswhere, but I'd recommend this one which @timheuer does a great job of keeping up to date.

Hi @heaths and @timheuer , yes I have tried used microsoft/setup-msbuild but face same issue that cannot find the MSBuild path. I have raised issue #101 and hope both of you can advise me on it whether any missed out from my side, thanks
