### ISSUE TITLE
Soon to be obsolete

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/setup-msbuild#28]
I started seeing warning about different actions in my workflow that set environment variables or update PATH. Just in case it is relevant for this Action, here are the resources for your investigation:

- https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

**Comment by timheuer** [comment]
Already merged the fix in #25
