### ISSUE TITLE
Xamarin Forms apk bacame corrupted

### ISSUE THREAD

**Issue by sergey19941201** [microsoft/setup-msbuild#29]
Having issues with msbuild. Seems it started to shrink and corrupt apk for some reason. Described question [here](https://stackoverflow.com/questions/64317086/apk-size-becomes-smaller-and-corrupted-with-nothing-changed-ingithub-actions).

**Comment by timheuer** [comment]
Hi @sergey19941201 this does not appear to be an issue with the project represented in this repo.  The MSBuild repo is https://github.com/dotnet/msbuild.  I'm closing this one here as not applicable to this project.

**Comment by sergey19941201** [comment]
@timheuer thanks. I created issue to their project. Can my problem be caused for any other reason? Maybe you have some extra ideas how to fix it.

**Comment by timheuer** [comment]
I forwarded your StackOverflow link to some folks internally
