### ISSUE TITLE
Using setup-msbuild with latest version of vs2019 but with vs2010 build tools

### ISSUE THREAD

**Issue by AraHaan** [microsoft/setup-msbuild#30]
So I got a project that now uses this action, however it depends on 3rd party dependencies that I cannot change which targets vs2010 build tools so in order to compile I would need for the actions to also include the vs2010 build tools like I have on my machine.

Hopefully it's just an yml setting change and not just an github action image issue on their windows-latest image.

the failed build is here: https://github.com/AraHaan/pthmgr/runs/1279113845?check_suite_focus=true

**Comment by timheuer** [comment]
Windows latest will have lates VS as installed by the hosted runner agents which will be VS 2019. If you need VS 2010 you may need to have a self-hosted agent.

**Comment by AraHaan** [comment]
ye I want the latest vs2019 but with the vs2010 build tools, since vs2019 is needed for the python extension building part of the code which exposes it all to python 3.9 as well.

**Comment by timheuer** [comment]
I don't think this is going to be possible on hosted agents.

**Comment by AraHaan** [comment]
Actually I found out it is, https://github.com/AraHaan/pthmgr/blob/master/.github/workflows/build.yml

**Comment by timheuer** [comment]
Closing this as you have resolved your needs.
