### ISSUE TITLE
Uses the deprecated add-path and set-env command

### ISSUE THREAD

**Issue by EoflaOE** [microsoft/setup-msbuild#34]
Hello,

According to GitHub, they have removed the `add-path` and `set-env` commands because there was a security issue. More information can be found here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`add-path` should be replaced with `addPath` and `set-env` should be replaced with `exportVariable`. Apparently, it uses `@actions/core` version `1.2.6`. More information: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

Because it uses the deprecated `add-path` and `set-env` commands, our GitHub Actions workflows which use `@microsoft/setup-msbuild` fail with an error referencing it.

The affected lines in affected files are found here:

https://github.com/microsoft/setup-msbuild/blob/f25dd68be285e78e89e662c0c6deee7f5065cbb3/dist/index.js#L1200

https://github.com/microsoft/setup-msbuild/blob/f25dd68be285e78e89e662c0c6deee7f5065cbb3/dist/index.js#L1184

And these are the failed workflows in our project:

https://github.com/EoflaOE/Kernel-Simulator/actions/runs/376949373
https://github.com/EoflaOE/Kernel-Simulator/actions/runs/376949371

This is a serious issue for us as it makes workflows that don't have `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable set to `true` unusable, especially for the project owners who seek for security like us.

**Comment by EoflaOE** [comment]
Well, looks like 1.0.2 fixed it. We'll use this version from now on. Updating all projects...

**Comment by timheuer** [comment]
Glad you found the fix! -- Yes, this was present in the core GitHub library (that pretty much every Action uses) and not directly called by this action's core code.  Either way, this is updated.
