### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by tdegeus** [microsoft/setup-msbuild#38]
I'm not sure if this is right place to ask. I'm seeking to use clang, now shipped with VS2019, on my GitHub action. Can this Action be used to this? How?

**Comment by timheuer** [comment]
This action cannot be used to do this as it isn't a general purpose action to find any tool.  We're keeping this specific to MSBuild tools. Sorry about that.  I'm not sure if clang could also be found with vswhere tools as well, perhaps @heaths may know.

**Comment by heaths** [comment]
vswhere is not designed to find specific tools, nor is that information stored in anyway it could. It find the root. You must combine the subdirectory yourself, or use a new enough version that supports the `-find` parameter.

**Comment by heaths** [comment]
vswhere is not designed to find specific tools, nor is that information stored in anyway it could. It find the root. You must combine the subdirectory yourself, or use a new enough version that supports the `-find` parameter.
