### ISSUE TITLE
Task should support prerelease versions of VS

### ISSUE THREAD

**Issue by wjk** [microsoft/setup-msbuild#45]
My dev workstation doubles as my self-hosted GitHub Actions runner. Installed upon it is VS2019 16.10 Preview 1.0. This is the only version of Visual Studio present on the machine. Unless this action specifies the `-prerelease` flag when it calls vswhere, no installations will be returned. However, there is no action parameter that lets me do this, and as such my workflow fails. Could support for this be added? Thanks!

**Comment by timheuer** [comment]
This is a good callout, confirming with @heaths that in current form there is no way to tweak the vs-version arg to get to it -- but I think this is a good request.

**Comment by heaths** [comment]
No, it's a separate switch. I recommend adding an optional parameter for it, since on custom agents that might have release and prerelease versions of VS, customers may want to ignore the prerelease (often unsupported) versions by default.
