### ISSUE TITLE
Rename v1 release to v1.0.0

### ISSUE THREAD

**Issue by EwoutH** [microsoft/setup-msbuild#49]
**Describe the bug**
Currently GitHub thinks the `v1` release is the latest release. This causes some unexpected behaviour if you use `microsoft/setup-msbuild@v1`, thinking you get the actual latest release (which is `v1.0.2`). Therefore I would propose to rename the `v1` release to `v1.0.0`, so that a plain `@v1` references the latest stable v1.x.x release again.

See https://github.com/microsoft/setup-msbuild/releases

![Screenshot_672](https://user-images.githubusercontent.com/15776622/115200793-e175f300-a0f4-11eb-9208-926d36cacbdf.png)

**Comment by timheuer** [comment]
The plan @v1 does reference the latest due to updating the tag.  Do you have a repo showing that it is not working as such?

**Comment by EwoutH** [comment]
Right. That's kind of confusing behavior I think, because the release notes and date now don't match the commit.

I would suggest removing/renaming the `v1` tag and continue using semantic versioning. That way if you just specify `microsoft/setup-msbuild@v1` it takes the latest v1.x.x release without needing to rename or retag commits.

**Comment by timheuer** [comment]
Hmm, the `@v1` relies on using a tag...I do not believe GitHub's action resolution by default assume semver and would do this automatically.  Hindsight here is 20/20 and the first release would have been cleaner, but I don't want to change things that would now BREAK people using the `@v1` moniker. See: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

**Comment by imba-tjd** [comment]
I completely disagree with @EwoutH. Recommend to see the most used action https://github.com/actions/checkout.

**Comment by timheuer** [comment]
Closing this out.  We released v1.0.3 and named a release specifically for that.  Thanks for providing the feedback here.
