### ISSUE TITLE
Planning to upgrade logo on GitHub Marketplace to Microsoft logo by end of May 2021

### ISSUE THREAD

**Issue by jpadams** [microsoft/setup-msbuild#54]
Team,
We are planning to upgrade the logo for all 13 GitHub Actions projects listed on the GitHub Marketplace to the official Microsoft logo.
![image](https://user-images.githubusercontent.com/3187222/118161788-dac95b80-b3d4-11eb-8627-476b8adb607a.png)

We'd like to make this change by the end of May 2021.

Please let us know if you have any objection, otherwise we'll proceed.

https://github.com/microsoft/raft-action
https://github.com/microsoft/sarif-actions
https://github.com/microsoft/powerplatform-actions
https://github.com/microsoft/psscriptanalyzer-action
https://github.com/microsoft/vs-intellicode
https://github.com/microsoft/setup-msbuild
https://github.com/microsoft/ps-rule
https://github.com/microsoft/RichCodeNavIndexer
https://github.com/microsoft/playwright-github-action
https://github.com/microsoft/DevSkim-Action
https://github.com/microsoft/infersharpaction
https://github.com/microsoft/android-app-size-diff
https://github.com/microsoft/variable-substitution

**Comment by timheuer** [comment]
@jpadams thanks for the heads up.  Is this to track that we as maintainers need to make this change? and how are you addressing any version change or just update the manifest icon only?

**Comment by jpadams** [comment]
> @jpadams thanks for the heads up. Is this to track that we as maintainers need to make this change? and how are you addressing any version change or just update the manifest icon only?

@timheuer This will only update the icon. We'll be making the change org-wide on the GitHub side.

**Comment by shmeadyy** [comment]
Hi @timheuer - just wanted to confirm that your team is okay with this logo change?  Please close out the issue if so, since we're tracking it internally on our side. Thanks!

**Comment by timheuer** [comment]
Hi @shmeadyy - I didn't think we had a choice 😂 -- I'm fine with it, happy to close this out.
