### ISSUE TITLE
How to compile cpp program and add additional includeDir?

### ISSUE THREAD

**Issue by xarthurx** [microsoft/setup-msbuild#55]
Hi, I tried to using MSBuild to compile my program with `msbuild /p:IncludePath="path/to/include"` where the path contains several external header files from a 3rd-party lib that my program need.

But the build process always said `Cannot open include file`, and it seems the folder is not included.

My local build works all fine, and Using `msbuild` locally also works fine. (The `AdditionalIncludeDir` is set in the VS file).

What is the correct way to include a 3rd-party lib source with `msbuild` ?

**Comment by timheuer** [comment]
Hi @xarthurx this does not appear to be an issue with this Action so I will close the issue.  If you are compiling with 3rd party libs, then the Actions runner needs to have those 3rd party libs present as well, so you will need to ensure those headers you need are present on the agent runner instance and the path is correct for your run.
