### ISSUE TITLE
Support for MSVS 2022

### ISSUE THREAD

**Issue by vadz** [microsoft/setup-msbuild#59]
Trying to use this action with the just added "windows-2022" environment (see https://github.com/actions/virtual-environments/issues/3949) doesn't work, msbuild is not found. It would be nice if it could be updated to support the latest version. TIA!

**Comment by timheuer** [comment]
Do you have a repo you can share with the settings you are using? Or just the default? I think this may be due to needing `-prerelease` available...which is #45 which I need to merge...

**Comment by heaths** [comment]
Yes, as long as the user didn't specify their own conflicting `vs-version` input.

**Comment by vadz** [comment]
> I think this may be due to needing `-prerelease` available...which is #45 which I need to merge...

Just noticed that you've merged it and [using it](https://github.com/vadz/wxWidgets/commit/be7f11074c4a5f76d103f049f0bb25e5ef87778d) does allow the action to find MSBuild in this environment, thanks! There are other problems in my builds, but they're unrelated to this action, so I think this issue can be closed now.

Thanks again!

**Comment by timheuer** [comment]
Awesome, thank you for confirming
