### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by Bassman2** [microsoft/setup-msbuild#63]
Please add support for Visual Studio 2022 on windows-2022.

I can not detect the new version with vswhere.exe and the base folder is moved to "Program Files".
As a workaround I currently use:

   ```
  runs-on: windows-2022
  ...
 - name: Add msbuild to PATH
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
```

**Comment by timheuer** [comment]
Hi there. This was added in the latest version. Add the argument `vs-prerelease: true` when using the action.
