### ISSUE TITLE
Examples still say @v1.1, should be updated to @v1.1.1

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/setup-msbuild#69]
Your examples here...
https://github.com/microsoft/setup-msbuild#example-usage

Still refer to @1.1, which no longer exists. Please update your Readme to reflect the latest version of v1.1.1.

**Comment by timheuer** [comment]
v1.1 tag was updated to match this.

-th
________________________________
From: Dominique Louis ***@***.***>
Sent: Sunday, November 21, 2021 11:06:24 AM
To: microsoft/setup-msbuild ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/setup-msbuild] Examples still say @1.1, should be updated to @1.1.1 (Issue #69)


You examples here...
https://github.com/microsoft/setup-msbuild#example-usage

Still refer to @1.1, which no longer exists. Please update your Readme to reflect the latest version. But also github actions can't find 1.1.1 either. So have you forgotten to publish it?

**Comment by CartBlanche** [comment]
@timheuer Sorry I'm unclear what you mean by `v1.1 tag was updated to match this.` 
Also worth noting that when I tried to using v1.1, or v1.1.1 in my yml, in both cases it says it can't find either, but it did fine v1.0.3.

**Comment by timheuer** [comment]
@CartBlanche Can you show me an existing log that is failing.  Please see as a working example: https://github.com/timheuer/ConsoleApp1/runs/4281871485?check_suite_focus=true#step:5:9 with the workflow setup as: https://github.com/timheuer/ConsoleApp1/blob/main/.github/workflows/build.yaml#L43-L44

**Comment by timheuer** [comment]
> Sorry I'm unclear what you mean by "v1.1 tag was updated to match this."

What this means is that you should use @v1.1 tagging and that tag/version has been matched to the latest patch release (@v1.1.1) -- this is preferred so that you can get patch releases and still use the 1.1 versioning.

**Comment by CartBlanche** [comment]
@timheuer I messed up the 1st time I tried v1.1. I realise my mistake now . Thanks for your help, using v1.1 is working now!
I have another set-up path question, but I'll close this issue and raise it there.
