### ISSUE TITLE
What extensions are installed when Visual Studio version is specified?

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/setup-msbuild#70]
I'm trying to use this Gitub Action to build a VS extension.
This VS extension uses some of the Xamarin tooling for debugging. My yml currently says...

```
with:
        vs-version: '[16.0, 17.0)'
```

but seems these don't include the Xamarin tooling to build iOS, Android apps, even though Xamarin is an MS product. 

Is there something like the below that I've missed??

```
with:
        vs-version: '[16.0, 17.0)'
        ms-extensions: 'xamarin-sdk'
```

**Comment by timheuer** [comment]
Hi @CartBlanche there is nothing you've missed in this particular action. Just to clarify as well this particular action is meant to discover and set the path of MSBuild ONLY. It is not a general purpose VS installer mechanism. It relies on the agent runners (either hosted or self-hosted) to have whatever is needed to complete the tasks.

For reference, the hosted agents install VS 2022 Enterprise and the components are identified here: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022.

If something is missing that is needed for your scenario for hosted images, that repo is the right place to request it for the hosted agents.  It _should_ be all of VS Enterprise and all components...but again if a component is missing that repo is the right place for that discussion/request.

I'm happy to take a look at a log result for any error message to see if I can offer an opinion, but going to close this issue as the runner software is managed elsewhere by GitHub.

**Comment by CartBlanche** [comment]
Totally understand @timheuer. I'll follow it up with them. Thanks again for all your help.

**Comment by CartBlanche** [comment]
In case others hit this same problem and end up here, I've raised an issue here - https://github.com/actions/virtual-environments/issues/4566
