### ISSUE TITLE
Is `vs-version` closing bracket ')' in the example is a typo?

### ISSUE THREAD

**Issue by ohcnkk** [microsoft/setup-msbuild#74]
In README.md, there is an example `vs-version: '[16.4,16.5)'` where the closing bracket `)` is a typo and should be `vs-version: '[16.4,16.5]'` instead?

**Comment by timheuer** [comment]
No that is correct. Agree it is weird but that is the syntax for vswhere. 

Also for GitHub hosted agents just a reminder that unless you are installing another version yourself you don’t need to specify that input as there will be only one version on the hosted agent.
