### ISSUE TITLE
MSBuild 17.1/17.2 not available on windows-latest/windows2022

### ISSUE THREAD

**Issue by HavenDV** [microsoft/setup-msbuild#77]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/3002068/154845461-3ddeb158-4ee2-4714-902e-af03e86a6dec.png">
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/3002068/154845425-0a668166-63e1-4f20-b480-a1b5e33d7b2f.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/3002068/154845439-5db6e0a5-2932-49f4-baeb-911beab89e70.png">

Latest desktop preview version:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/3002068/154845559-1b2dd54f-1e57-49a4-90ab-847d67a8f8c2.png">

**Comment by HavenDV** [comment]
Based on this issue, this was recently available - https://github.com/microsoft/setup-msbuild/issues/73

**Comment by HavenDV** [comment]
Seems like I need to use this: https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022

**Comment by timheuer** [comment]
Hi @HavenDV the hosted agents do not yet have the updated 17.1 release (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022).  17.2 is in preview and wouldn't be on the release agents yet.

Is something specifically needed from the 17.1/17.2 releases for MSBuild for you that is a blocker?

**Comment by HavenDV** [comment]
> Is something specifically needed from the 17.1/17.2 releases for MSBuild for you that is a blocker?

This is a very specific problem. MSBuild 17.0 is not able to build a library with a source generator that has a generation time dependency as a .Net Standard 1.0 library (and therefore contains .Net Standard 1.0 dependencies in the analyzers/dotnet/cs folder). 17.2 successfully builds it. I don't know in which version exactly they solved it.

**Comment by HavenDV** [comment]
Solution, in case anyone stumbles upon this issue while looking for a solution to theirs:
```yaml
runs-on: windows-latest

    - name: Download build tools
      run: Invoke-webrequest
        -uri https://aka.ms/vs/17/pre/vs_buildtools.exe
        -OutFile vs_buildtools.exe
      shell: powershell

    - name: Install build tools
      run: .\vs_buildtools.exe
        --wait
        --norestart
        --passive
        --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
        --includeOptional
        --includeRecommended
        --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools
        --add Microsoft.VisualStudio.Workload.MSBuildTools
        --add Microsoft.VisualStudio.Workload.NativeDesktop
        --add Microsoft.VisualStudio.Workload.NetCoreTools
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: ${{ inputs.vs-prerelease }}
```
<img width="705" alt="image" src="https://user-images.githubusercontent.com/3002068/154889424-2ee92530-c3cc-46c1-8b33-d0de79eb8476.png">

I think the setup arguments can be greatly optimized for your specific task, but this works for me.

Based on:
https://gist.github.com/tushartushar/f327abdba580511c0a996db4f4faf0d8
https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022
It's the ru-RU page, but it contains the preview link: https://docs.microsoft.com/ru-ru/visualstudio/install/advanced-build-tools-container?view=vs-2022

**Comment by timheuer** [comment]
Thanks for the added info @HavenDV!
