### ISSUE TITLE
Running msbuild with PFX password without quotes will dump it into logs if password has invalid chars.

### ISSUE THREAD

**Issue by wildone** [microsoft/setup-msbuild#81]
When msbuild fails if PFX password has invalid chars it will dump password info console.

Is this expected? Is there any toggle to stop this from happening? (Yes I will double quote the password)
 
Thank you!

FYI some how I have a felling this is wrong place to post this, happy to post elsewhere, if you direct me.

**Comment by timheuer** [comment]
Hi @wildone, yes I think you have a basic MSBuild question not related to this GitHub Action.  I would transfer the issue, but cannot in cross-organization.  Please log this issue on https://github.com/dotnet/msbuild

**Comment by wildone** [comment]
@timheuer just came to copy the text into ticket in there :D thanks
