### ISSUE TITLE
Transferring projects with MFC Library from VS2019 to VS2022

### ISSUE THREAD

**Issue by caibinwav123456** [microsoft/setup-msbuild#82]
When I‘m recently building my MFC based project on an github hosted agent with label "windows-latest", I got the following error ever since the VS version has switched to VS2022：

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(479,5): error MSB8041: MFC libraries are required for this project. Install them from the Visual Studio installer (Individual Components tab) for any toolsets and architectures being used. 

So is the MFC Library simply not installed on this version of VS? What shall I do now?

**Comment by timheuer** [comment]
This looks unrelated to `setup-msbuild` so I will close it but as a suggestion change your agent to `windows-2019` and see if resolves.
