### ISSUE TITLE
WiX Light can't find a downloaded github actions artifact

### ISSUE THREAD

**Issue by adlud** [microsoft/setup-msbuild#83]
In one step of a github actions job, I download an artifact that was uploaded in a previous job. I see these messages in the workflow output:

- Artifact Executable_file was downloaded to D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe
- Artifact download has finished successfully

In a subsequent step of the same job, I run msbuild on a *.wixproj file. Candle runs without error, but Light fails with this error:

- error LGHT0103: The system cannot find the file 'D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe'.

The paths match, so the file should be found.

Here is some more info, in case it helps.

The relevant sections of the workflow .yml file:

`- name: Download executable file`
`  uses: actions/download-artifact@v3`
`  with:`
`    name: Executable_file`
`    path: ./PCMateSetup/PCMPLUS.exe`

`- name: Build PCMateSetup`
`  run: |`
`    msbuild /m /p:MajorVer="${{env.majVer}}" /p:MinorVer="${{env.minVer}}" /p:BuildVer="${{env.bldVer}}" /p:ProtoVer="0" /p:GithubBld="true" /p:Configuration=${{env.BUILD_CONFIGURATION}} /v:n ${{env.SOLUTION_FILE_PATH}}\PCMateSetup\PCMateSetup.wixproj`

From the .wxs files:

`<File Id="file.instDir.PCMPLUSExecutable" Vital="yes" Source="$(var.ProjectDir)PCMPLUS.exe" KeyPath="yes" />`

And also from the output messages:

- ProjectDir: D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\

Let me know if any more info is needed. Thanks for taking a look.

**Comment by timheuer** [comment]
Hi @adlud this sounds like msbuild is found and doing its job and your issue is actually with light. I’d recommend logging an issue on the WiX project. 

Based on the information you provided it does not seem related to this action so unfortunately we cannot help here.

**Comment by adlud** [comment]
Ok @timheuer , I will do that.
