### ISSUE TITLE
It's not getting the version you want when putting the msbuild version.

### ISSUE THREAD

**Issue by Feeh03114** [microsoft/setup-msbuild#95]
![image](https://user-images.githubusercontent.com/58147419/200063489-135bee5f-b50c-4900-96bc-45cefde3677b.png)

**Comment by timheuer** [comment]
Can you provide more information here @Feeh03114? -- what specifically are you putting in that is failing and on what hosted agent version?

**Comment by timheuer** [comment]
Need more info

**Comment by Feeh03114** [comment]
When I type the build version it keeps getting the 2022 version, even though I want the 2019 or 2015 version.

I saw that when he downloaded MsBuild he would always download the most received version because it was like this:
"-products * -requires Microsoft.Component.MSBuild -property installationPath -latest".

**Comment by timheuer** [comment]
@Feeh03114 - please see documentation here: https://github.com/microsoft/setup-msbuild#specifying-specific-versions-of-visual-studio-optional

If you are using the GitHub hosted runners, there will only be one version of Visual Studio on the machine, hence requesting a version is not going to yield any results you may expect.  The version selector option is mostly for those doing self-hosted runners where they control what is on the machine and may have multiple versions.  And even then you need to specify in the correct format.

But GitHub Actions hosted runners will only have one version.  For `windows-latest` or `windows-2022` that will be Visual Studio 2022.  And for `windows-2019` that will be Visual Studio 2019.  Both specify what software is on the machine here:

- [windows-latest/windows-2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022)
- [windows-2019](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019)

I hope this helps.
