### ISSUE TITLE
Update Node.js version from 12 to 16

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/setup-msbuild#98]
After pipeline build, that used MSBuild you can see the warning message:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/50652041/201080144-3005df72-f7ce-43c7-9392-5ff82fa920d0.png">

The message itself:
**Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout**

**Comment by timheuer** [comment]
This has already been implemented. Please update the tag you are using

**Comment by LeftTwixWand** [comment]
This is strange, but I'm using [setup-msbuild@v1.1.3](https://github.com/LeftTwixWand/Inventory/blob/b72910e90508558b59de3d93de0aaabfe87d7476/.github/workflows/ci.yml#L21).
Or which tag do you mean?

**Comment by timheuer** [comment]
@LefTwixWand - yes `microsoft/setup-msbuild@v1.1.3` or `microsoft/setup-msbuild@v1` should work.  If you have a run that is still showing that warning *from this action* please send me a link to the full logs if possible.  It could be another action that is emitting that as well -- hard to tell from your screenshot, but here's an example of it running with both these tags and no warnings.  https://github.com/timheuer/test-console/actions/runs/3455751641/jobs/5767992347

**Comment by LeftTwixWand** [comment]
Hey, this is the pipeline, where you can see the warning message:
https://github.com/LeftTwixWand/Inventory/actions/runs/3460231983

**Comment by timheuer** [comment]
Yep, it is a different action:
![image](https://user-images.githubusercontent.com/4821/201667329-dcd959a5-1786-41fe-af98-6141df8f5be6.png)

update checkout to `@v3`

**Comment by LeftTwixWand** [comment]
Oh, sorry. My fault😅😅
Thank you for help)

**Comment by timheuer** [comment]
> I am new to using github actions for our Visual Studio project, so I had my workflow generated by a friendly button in githubs action tabs. This however (still?) used the @1.0.2 tag so it also ran into this warning.
> 
> Can you update the template (or the generator) to use a "current" version of this action or is there another way to let github know about it?

Which template did you use? I can certainly try to hunt down the folks and update it.

**Comment by timheuer** [comment]
Found it @Patru -- submitted a PR to change it.  Thanks for the note! https://github.com/actions/starter-workflows/pull/2116
